server {
    listen 4200;
    # listen 192.168.0.127:4200;
    server_name 192.168.0.127;
    # server_name localhost;
    # server_name http://192.168.0.106;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

# SSL configuration for Angular app
# server {
#     listen 4200 ssl;
#     # server_name docmaccdentalclinic.local;
#     # server_name 192.168.1.2;
#     server_name http://192.168.0.106;

#     ssl_certificate /etc/nginx/ssl/server.crt;
#     ssl_certificate_key /etc/nginx/ssl/server.key;

#     location / {
#         root /usr/share/nginx/html;
#         index index.html;
#         try_files $uri $uri/ /index.html;
#     }
# }
