server {
    listen 4200;
    server_name 192.168.0.127; //Doc MACC Server
    # server_name kennethmacaraeg317.com;
    # server_name 192.168.1.57;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

